// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Alfred Jean LLC

// AUTO-GENERATED by tests/capture/generate.ts — do not edit manually

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod specs;

#[test]
fn cli_help_doctor() {
    specs::assert_cli_starts_with("v2.1.29", "help-doctor", &["doctor", "--help"]);
}

#[test]
fn cli_help_install() {
    specs::assert_cli_starts_with("v2.1.29", "help-install", &["install", "--help"]);
}

#[test]
fn cli_help_mcp_add() {
    specs::assert_cli_starts_with("v2.1.29", "help-mcp-add", &["mcp", "add", "--help"]);
}

#[test]
fn cli_help_mcp_serve() {
    specs::assert_cli_starts_with("v2.1.29", "help-mcp-serve", &["mcp", "serve", "--help"]);
}

#[test]
fn cli_help_mcp() {
    specs::assert_cli_starts_with("v2.1.29", "help-mcp", &["mcp", "--help"]);
}

#[test]
fn cli_help_plugin_marketplace() {
    specs::assert_cli_starts_with(
        "v2.1.29",
        "help-plugin-marketplace",
        &["plugin", "marketplace", "--help"],
    );
}

#[test]
fn cli_help_plugin() {
    specs::assert_cli_starts_with("v2.1.29", "help-plugin", &["plugin", "--help"]);
}

#[test]
fn cli_help_setup_token() {
    specs::assert_cli_starts_with("v2.1.29", "help-setup-token", &["setup-token", "--help"]);
}

#[test]
fn cli_help_update() {
    specs::assert_cli_starts_with("v2.1.29", "help-update", &["update", "--help"]);
}

#[test]
fn cli_help() {
    specs::assert_cli_starts_with("v2.1.29", "help", &["--help"]);
}

#[test]
fn cli_version() {
    specs::assert_cli_starts_with("v2.1.29", "version", &["--version"]);
}
