// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Alfred Jean LLC

// AUTO-GENERATED by tests/capture/generate.ts — do not edit manually

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod specs;

#[test]
fn tmux_ctrl_c_exit_hint() {
    specs::run_tmux_spec("v2.1.29", "ctrl-c-exit-hint", &["ctrl_c_exit_hint"]);
}

#[test]
fn tmux_ctrl_d_exit_hint() {
    specs::run_tmux_spec("v2.1.29", "ctrl-d-exit-hint", &["ctrl_d_exit_hint"]);
}

#[test]
fn tmux_ctrl_z_suspend() {
    specs::run_tmux_spec("v2.1.29", "ctrl-z-suspend", &["ctrl_z_suspend"]);
}

#[test]
fn tmux_trust_prompt() {
    specs::run_tmux_spec("v2.1.29", "trust-prompt", &["trust_prompt"]);
}
